nome = input ('Qual é seu nome?')
idade = input ('Qual é a sua idade?')
peso = input ('Qual é seu peso?')
sexo = input ('Qual é o seu sexo?')
escola = input ('Estudas no la benediction?')
section = input ('Que formação voce faz?')
print (nome, idade, peso, sexo, escola, section)
