nome = input('Qual é seu nome?')
idade = input('Qual é a sua idade?')
peso = input('Qual é seu peso?')
escola = input('Estudas no la benediction?')
section = input('Que formação voce faz?')
print('Olá', nome, ',voce tem', idade, ',voce pesa', peso, ',estas a fazendo a formação de', section, ', correto!')
