print('\033[1;35m=' * 55)
print('Desafio#4')
print('=' * 55)
print('\033[mOlá eu sou o leitore de digitos, por favor digite algo ')
n = input('\033[1;33mDigite algo\033[m ')
print(f'\033[32mO tipo primitivo do seu digito é {type(n)}\033[m')
print(f'\033[31mO digito {n} é um numero ', n.isnumeric())
print(f'O digito {n} é alphabetico', n.isalpha())
print(f'O digito {n} é alphanumerico', n.isalnum())
print(f'O digito {n} esta em mauscola', n.isupper())
print(f'O digito {n} esta em miniscula', n.islower())
print(f'O digito {n} esta capitalisada', n.istitle(), '\033[m')
